<?php

namespace AppBundle\Repository;

/**
 * TaskCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
